services:
  frontend:
    build:
      context: ./frontend/frontEstoque
      dockerfile: Dockerfile.dev
    
    ports:
      - "3005:5173"

    volumes:
      - ./frontend/frontEstoque:/app
      #evita que a pasta node_modules local sobrescreva a do contêiner
      - /app/node_modules

  backend:
    build:
      context: ./backend/Gerenciamento_Estoque_Desafio_3
      dockerfile: Dockerfile.dev

    volumes:
      - ./backend/Gerenciamento_Estoque_Desafio_3:/app
      # Mapeia o cache do Maven para acelerar builds futuros
      - ~/.m2:/root/.m2