services:
  postgres-db:
    image: postgres:14-alpine
    container_name: estoque_postgres_db
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    networks:
      - app-network
  
  backend:
    container_name: estoque_backend
    build:
      context: ./backend/Gerenciamento_Estoque_Desafio_3
    restart: always
    depends_on:
      - postgres-db
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      
      SPRING_FLYWAY_SCHEMAS: public
    networks:
      - app-network
  
  frontend:
    container_name: estoque_frontend
    build:
      context: ./frontend/frontEstoque
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local